[theme]
primaryColor = "#123C69"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2C3E50"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
